version: '3.8'


services:
  mongo:
    container_name: thread-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sjana7797
      MONGO_INITDB_ROOT_PASSWORD: 7797

volumes:
  mongo_data: